POST web-client:@localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope=*&username=user1@mail.com&password=123456

> {%
  var accessToken = response.body.access_token;
  client.global.set("accessToken", accessToken);
%}

###

GET localhost:8081/users/me
Authorization: bearer {{accessToken}}

###

GET localhost:8082/resources/1
Authorization: bearer {{accessToken}}

###

POST localhost:8081/users/me/signup
Content-Type: application/json

{
  "name": "John Smith",
  "email": "jsmith@mail.com",
  "password": "123456"
}

###

POST web-client:@localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope=*&username=jsmith@mail.com&password=123456

> {%
  var accessToken = response.body.access_token;
  client.global.set("accessToken", accessToken);
%}

###

GET localhost:8082/resources/2
Authorization: bearer {{accessToken}}

###

